# Generated by Django 4.1.4 on 2023-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='author',
        ),
        migrations.AddField(
            model_name='videopost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data'),
        ),
    ]
