# Generated by Django 4.1.4 on 2023-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('summary', models.CharField(max_length=150, verbose_name='summary')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='image')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
        ),
    ]
