# Generated by Django 4.1.4 on 2023-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data'),
        ),
    ]
